### ISSUE TITLE
rpc error code

### ISSUE THREAD

**Issue by Kerimoss** [clarkzjw/starlink_exporter#51]
Hi,

Firstly, thank you for your work on starlink_exporter.

I'm encountering an issue when using the tool. The error message I receive is: 

`failed to collect dish location: rpc error: code = PermissionDenied desc = GetLocation requests are not enabled on this device.`

Do you have any idea how I might resolve this? Is it related to API permissions or a specific configuration of the device?

Thank you in advance for your assistance.

Best regards,

Kerimoss

**Comment by clarkzjw** [comment]
Hi, there is a setting in the Starlink mobile app, "Advanced->debug data", "Starlink location->allow access on local network". Can you try to enable this setting and try again?

**Comment by Kerimoss** [comment]
Hi,

I just wanted to follow up and let you know that your suggestion worked perfectly! 
I really appreciate your quick and effective support. I'm grateful for your help.

Thanks again!

**Comment by clarkzjw** [comment]
@Kerimoss Good to know it helps!
